// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sugobltnispppfgdwyhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1Z29ibHRuaXNwcHBmZ2R3eWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4OTg4MjAsImV4cCI6MjA3MDQ3NDgyMH0.amWW27tbBHOesvrviugZ2VJl5Ax-fiH6oXJBz9JIW4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});